In [1]:
import torch
from torchvision.models import resnet18
import pickle
import numpy as np

In [11]:
count_mask = torch.full(size=(20,), fill_value=256, dtype=torch.float)
count_mask2 = torch.full(size=(20,), fill_value=256, dtype=torch.float)
condition = torch.randn(size=(20,)) < 0
count_mask_update = torch.logical_and(torch.eq(count_mask, 256), torch.eq(condition, True))
count_mask[count_mask_update] = 1

In [10]:
torch.std(count_mask)

tensor(130.1565)

In [12]:
mask = torch.eq(count_mask, 256)

In [13]:
mask = ~mask

In [17]:
x = torch.randn(size=(100,))

In [20]:
mask = torch.tensor([1,2,3,4,5,6])
x[mask]

tensor([-0.4223, -1.3558, -0.1775,  0.5800, -1.0721,  0.3710])

In [15]:
mask.shape

torch.Size([20])

In [58]:
torch.full(size=(20,), fill_value=256)

tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256,
        256, 256, 256, 256, 256, 256])

In [64]:
mask = torch.concat((count_mask, count_mask2), dim=0)

In [62]:
mask = ~mask

In [63]:
mask

tensor([-257, -257, -257, -257, -257, -257, -257, -257, -257, -257, -257, -257,
        -257, -257, -257, -257, -257, -257, -257, -257, -257, -257, -257, -257,
        -257, -257, -257, -257, -257, -257, -257, -257, -257, -257, -257, -257,
        -257, -257, -257, -257])